### ISSUE TITLE
BLDC ESC

### ISSUE THREAD

**Issue by samuk** [701lab/ESP32-robot-car-controller#1]
Do you have any interest in getting this code running on this board: https://github.com/rosmo-robot/Open-Core-M5stack/tree/main/v2.1#readme

communicating with  this firmware: https://github.com/rosmo-robot/Rosmo_ESC_firmware

On this ESC https://github.com/rosmo-robot/Rosmo_ESC

I could arrange to get you parts if you'd hack it together.

Update: I flashed it to my Open Core board, It brings up Wifi network and I can connect, but no webpage is loaded

**Comment by Trimple** [comment]
Hello, sorry for the late response.

We can definitely try using the firmware on your board! But we will definitely need to make some updates. What are you most interested in? Getting the web page running?

Regarding your update, what IP address did you use to check the web-page? The correct one is 192.168.4.1.

I would definitely like to play around with your hardware if this is still relevant.

**Comment by Trimple** [comment]
ah, I actually think I know, why it doesn't load the web-page! Ip-address assumption was quite silly from my side. To get the web-page you need to load it to the SPIFFS.

**Comment by Trimple** [comment]
It can be easily done using PlatformIO:
1. open the project in VSCode;
2. open PlatformIO menu
![image](https://user-images.githubusercontent.com/29435805/169287140-4d9d5e7a-2ac8-4245-be12-d4a4539ee914.png)

3. press "Upload Filesystem Imga" option and wait for it to finish.
![image](https://user-images.githubusercontent.com/29435805/169287276-63647a54-bd52-4fe6-81d3-5e6d35b627bd.png)

After that you should have working web-page on your device.

**Comment by Trimple** [comment]
I didn't thought someone would be interested in this project, which is one again silly from my part. I will update the readme to better explain how to run the project for the first time and how it can be enchanced.

**Comment by Trimple** [comment]
Updated the readme. Hope now it will be more intuitive

**Comment by samuk** [comment]
Ah great thanks, will give it a go later! I actually just posted out the last of the boards yesterday. We should have a few more produced soon so I can let you know when that happens,

**Comment by Trimple** [comment]
Sounds good!

**Comment by samuk** [comment]
Cool that works, thanks.

So it looks like we mostly need to edit from here to make it work: https://github.com/701lab/ESP32-robot-car-controller/blob/main/src/main.cpp#L60

With the I2C stuff from https://github.com/rosmo-robot/Rosmo_ESC_firmware/blob/master/src/RosmoI2CCommander.h#L15

**Comment by Trimple** [comment]
Yes, this is correct. You will need to enable desired I2C, disable UART and change the communication code at the location you pointed to.
